# Generated by Django 3.1.1 on 2022-09-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='line_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
